const std = @import("std");
const builtin = @import("builtin");

fn linkPlatformLibs(compile: *std.Build.Step.Compile, target: std.Build.ResolvedTarget) void {
    compile.root_module.link_libc = true;
    if (target.result.os.tag == .windows) {
        // Winsock symbols are provided by these system libraries on Windows.
        compile.root_module.linkSystemLibrary("ws2_32", .{});
        compile.root_module.linkSystemLibrary("mswsock", .{});
    }
}

/// Recursively embeds a directory into an executable at build time.
///
/// Walks `rootDir` (relative to the project root) with the host
/// filesystem, sorts entries deterministically by relative path, reads
/// every file, and generates a manifest module importable as
/// `importName`:
///
/// ```zig
/// const embedded = @import("embedWebsite");
/// try httpx.assets.registerEmbeddedDir(allocator, &embedded.files);
/// ```
///
/// `embedded.files` matches `httpx.assets.EmbeddedFile`
/// (`{ path, content }`), so one call registers the whole tree. Logical
/// paths are portable `/`-separated relatives and file bytes are inlined
/// as escaped string literals, keeping the generated manifest portable
/// across machines. MIME types and sizes derive at runtime through the
/// shared MIME system and `content.len` (single source of truth).
/// Asset names containing `"` and files over 16 MiB are skipped.
fn embedDir(b: *std.Build, exe: *std.Build.Step.Compile, httpxModule: *std.Build.Module, rootDir: []const u8, importName: []const u8) void {
    const allocator = b.allocator;
    var relPaths: std.ArrayList([]u8) = .empty;
    defer {
        for (relPaths.items) |p| allocator.free(p);
        relPaths.deinit(allocator);
    }

    const io = b.graph.io;
    const cwd: std.Io.Dir = .cwd();
    var root = cwd.openDir(io, rootDir, .{ .iterate = true }) catch return;
    defer root.close(io);
    var walker = root.walk(allocator) catch return;
    defer walker.deinit();
    while (walker.next(io) catch null) |entry| {
        if (entry.kind != .file) continue;
        var p = allocator.dupe(u8, entry.path) catch return;
        for (p, 0..) |_, i| {
            if (p[i] == '\\') p[i] = '/';
        }
        if (std.mem.indexOfScalar(u8, p, '"') != null) continue;
        relPaths.append(allocator, p) catch return;
    }
    std.mem.sort([]u8, relPaths.items, {}, struct {
        fn less(_: void, x: []u8, y: []u8) bool {
            return std.mem.order(u8, x, y) == .lt;
        }
    }.less);

    var out: std.ArrayList(u8) = .empty;
    defer out.deinit(allocator);
    out.print(allocator, "// Generated by build.zig embedDir from \"{s}\" - do not edit.\n", .{rootDir}) catch return;
    out.appendSlice(allocator, "const httpx = @import(\"httpx\");\n") catch return;
    out.appendSlice(allocator, "pub const files = [_]httpx.assets.EmbeddedFile{\n") catch return;
    for (relPaths.items) |rel| {
        const content = root.readFileAlloc(io, rel, allocator, .limited(16 * 1024 * 1024)) catch continue;
        defer allocator.free(content);
        out.print(allocator, "    .{{ .path = \"{s}\", .content = \"", .{rel}) catch return;
        for (content) |c| {
            switch (c) {
                '\n' => out.appendSlice(allocator, "\\n") catch return,
                '\r' => out.appendSlice(allocator, "\\r") catch return,
                '\t' => out.appendSlice(allocator, "\\t") catch return,
                0x20...0x7e => {
                    if (c == '"' or c == '\\') {
                        out.print(allocator, "\\{c}", .{c}) catch return;
                    } else {
                        out.append(allocator, c) catch return;
                    }
                },
                else => out.print(allocator, "\\x{x:0>2}", .{c}) catch return,
            }
        }
        out.appendSlice(allocator, "\" },\n") catch return;
    }
    out.appendSlice(allocator, "};\n") catch return;

    const wf = b.addWriteFiles();
    const manifestName = std.fmt.allocPrint(allocator, "{s}.zig", .{importName}) catch return;
    _ = wf.add(manifestName, out.items);
    exe.root_module.addAnonymousImport(importName, .{
        .root_source_file = wf.getDirectory().path(b, manifestName),
        .imports = &.{
            .{ .name = "httpx", .module = httpxModule },
        },
    });
}

/// Build configuration for httpx.zig - Production-ready HTTP library for Zig
/// Supports HTTP/1.1, HTTP/2, HTTP/3 with TLS, connection pooling, and more.
/// Third-party import names for src/httpx.zig, paired positionally with
/// the dependency modules below.
const dep_names = [_][]const u8{ "zstd", "brotli", "env", "loaders", "treesitter" };

/// Wires the third-party imports httpx.zig expects into `m`.
fn addHttpxImports(m: *std.Build.Module, deps: []const *std.Build.Module) void {
    for (dep_names, deps) |name, dep| m.addImport(name, dep);
}

/// Creates the httpx root module (src/httpx.zig) with its third-party
/// imports wired in. The tests, the static library and the cross-target
/// sweep each need this same module, so it is built in one place.
fn httpxRootModule(
    b: *std.Build,
    target: std.Build.ResolvedTarget,
    optimize: std.builtin.OptimizeMode,
    deps: []const *std.Build.Module,
) *std.Build.Module {
    const m = b.createModule(.{
        .root_source_file = b.path("src/httpx.zig"),
        .target = target,
        .optimize = optimize,
    });
    addHttpxImports(m, deps);
    return m;
}

pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});

    const optimize = b.standardOptimizeOption(.{});

    const zstdDep = b.dependency("zstd", .{
        .target = target,
        .optimize = optimize,
    });

    const brotliDep = b.dependency("brotli", .{
        .target = target,
        .optimize = optimize,
    });

    const envDep = b.dependency("env", .{
        .target = target,
        .optimize = optimize,
    });

    const loadersDep = b.dependency("loaders", .{
        .target = target,
        .optimize = optimize,
    });

    const treesitterDep = b.dependency("treesitter", .{
        .target = target,
        .optimize = optimize,
    });

    const deps = [_]*std.Build.Module{
        zstdDep.module("zstd"),
        brotliDep.module("brotli"),
        envDep.module("env"),
        loadersDep.module("loaders"),
        treesitterDep.module("treesitter"),
    };

    // Create the public module that will be exported as "httpx" to consumers.
    // Dependencies must be added here so they propagate to downstream packages.
    const httpxModule = b.addModule("httpx", .{
        .root_source_file = b.path("src/httpx.zig"),
    });
    addHttpxImports(httpxModule, &deps);

    const examples = [_]struct { name: []const u8, path: []const u8 }{
        .{ .name = "simple-get", .path = "examples/simpleGet.zig" },
        .{ .name = "post-json", .path = "examples/postJson.zig" },
        .{ .name = "custom-headers", .path = "examples/customHeaders.zig" },
        .{ .name = "connection-pool", .path = "examples/connectionPool.zig" },
        .{ .name = "redirect", .path = "examples/redirect.zig" },
        .{ .name = "streaming", .path = "examples/streaming.zig" },
        .{ .name = "multipart", .path = "examples/multipart.zig" },
        .{ .name = "custom-responses", .path = "examples/customResponses.zig" },
        .{ .name = "browser-demo-server", .path = "examples/browserDemoServer.zig" },
        .{ .name = "simple-server", .path = "examples/simpleServer.zig" },
        .{ .name = "routing-demo", .path = "examples/routingDemo.zig" },
        .{ .name = "static-files", .path = "examples/staticFiles.zig" },
        .{ .name = "health-check", .path = "examples/healthCheck.zig" },
        .{ .name = "tls-get", .path = "examples/tlsGet.zig" },
        .{ .name = "resolve", .path = "examples/resolve.zig" },
        .{ .name = "openapi", .path = "examples/openapi.zig" },
        .{ .name = "http10-client", .path = "examples/http10Client.zig" },
        .{ .name = "http11-client", .path = "examples/http11Client.zig" },
        .{ .name = "http11-server", .path = "examples/http11Server.zig" },
        .{ .name = "http2-client", .path = "examples/http2Client.zig" },
        .{ .name = "http2-tls", .path = "examples/http2Tls.zig" },
        .{ .name = "http2-multiplex", .path = "examples/http2Multiplex.zig" },
        .{ .name = "http3-client", .path = "examples/http3Client.zig" },
        .{ .name = "http3-quic", .path = "examples/http3Quic.zig" },
        .{ .name = "http3-0rtt", .path = "examples/http3ZeroRtt.zig" },
        .{ .name = "ftp-client", .path = "examples/ftpClient.zig" },
        .{ .name = "live-static-watcher", .path = "examples/liveStaticWatcher.zig" },
        .{ .name = "docs-server", .path = "examples/docsServer.zig" },
        .{ .name = "graphql-server", .path = "examples/graphqlServer.zig" },
        .{ .name = "auth-and-errors", .path = "examples/authAndErrors.zig" },
        .{ .name = "spa-fallback", .path = "examples/spaFallback.zig" },
        .{ .name = "websocket-server", .path = "examples/websocketServer.zig" },
        .{ .name = "sse-server", .path = "examples/sseServer.zig" },
        .{ .name = "session-server", .path = "examples/sessionServer.zig" },
        .{ .name = "metrics-server", .path = "examples/metricsServer.zig" },
        .{ .name = "interceptor-example", .path = "examples/interceptorExample.zig" },
        .{ .name = "cookie-server", .path = "examples/cookieServer.zig" },
        .{ .name = "concurrent-demo", .path = "examples/concurrentDemo.zig" },
        .{ .name = "proxy-demo", .path = "examples/proxyDemo.zig" },
        .{ .name = "dns-demo", .path = "examples/dnsDemo.zig" },
        .{ .name = "compression-demo", .path = "examples/compressionDemo.zig" },
        .{ .name = "retry-demo", .path = "examples/retryDemo.zig" },
        .{ .name = "custom-server", .path = "examples/customServer.zig" },
        .{ .name = "cors-server", .path = "examples/corsServer.zig" },
        .{ .name = "rate-limit-server", .path = "examples/rateLimitServer.zig" },
        .{ .name = "helmet-server", .path = "examples/helmetServer.zig" },
        .{ .name = "body-parser-server", .path = "examples/bodyParserServer.zig" },
        .{ .name = "tls-server", .path = "examples/tlsServer.zig" },
        .{ .name = "https-client", .path = "examples/httpsClient.zig" },
        .{ .name = "tls12-client", .path = "examples/tls12Client.zig" },
        .{ .name = "tls13-client", .path = "examples/tls13Client.zig" },
        .{ .name = "tls-mtls", .path = "examples/tlsMtls.zig" },
        .{ .name = "dns-cache", .path = "examples/dnsCache.zig" },
        .{ .name = "ftp-server", .path = "examples/ftpServer.zig" },
        .{ .name = "download", .path = "examples/download.zig" },
        .{ .name = "download-info", .path = "examples/downloadInfo.zig" },
        .{ .name = "download-verify", .path = "examples/downloadVerify.zig" },
        .{ .name = "download-resume", .path = "examples/downloadResume.zig" },
        .{ .name = "download-existing", .path = "examples/downloadExisting.zig" },
        .{ .name = "download-custom-progress", .path = "examples/downloadCustomProgress.zig" },
        .{ .name = "download-batch", .path = "examples/downloadBatch.zig" },
        .{ .name = "download-update", .path = "examples/downloadUpdate.zig" },
        .{ .name = "download-checksum-file", .path = "examples/downloadChecksumFile.zig" },
        .{ .name = "ftp-download", .path = "examples/ftpDownload.zig" },
        .{ .name = "parse-html", .path = "examples/parseHtml.zig" },
        .{ .name = "html-client", .path = "examples/htmlClient.zig" },
        .{ .name = "html-select", .path = "examples/htmlSelect.zig" },
        .{ .name = "html-extract", .path = "examples/htmlExtract.zig" },
        .{ .name = "html-stream", .path = "examples/htmlStream.zig" },
        .{ .name = "html-file", .path = "examples/htmlFile.zig" },
        .{ .name = "html-transform", .path = "examples/htmlTransform.zig" },
        .{ .name = "file-watcher", .path = "examples/fileWatcher.zig" },
        .{ .name = "live-reload", .path = "examples/liveReload.zig" },
        .{ .name = "static-site", .path = "examples/staticSite.zig" },
        .{ .name = "static-embedded", .path = "examples/staticEmbedded.zig" },
        .{ .name = "spa-server", .path = "examples/spaServer.zig" },
        .{ .name = "development-server", .path = "examples/developmentServer.zig" },
        .{ .name = "connectivity", .path = "examples/connectivity.zig" },
        .{ .name = "full-integration", .path = "examples/fullIntegration.zig" },
        .{ .name = "template-basic", .path = "examples/web/templates/basic/main.zig" },
        .{ .name = "template-inheritance", .path = "examples/web/templates/inheritance/main.zig" },
        .{ .name = "template-loops", .path = "examples/web/templates/loops/main.zig" },
        .{ .name = "template-includes", .path = "examples/web/templates/includes/main.zig" },
        .{ .name = "template-live-reload", .path = "examples/web/templates/live_reload/main.zig" },
        .{ .name = "template-jinja", .path = "examples/web/templates/jinja/main.zig" },
        .{ .name = "website", .path = "examples/website/main.zig" },
    };

    const buildAllExamples = b.step("build-all-examples", "Build all example executables");

    inline for (examples) |example| {
        const exe = b.addExecutable(.{
            .name = example.name,
            .root_module = b.createModule(.{
                .root_source_file = b.path(example.path),
                .target = target,
                .optimize = optimize,
            }),
        });
        exe.root_module.addImport("httpx", httpxModule);
        linkPlatformLibs(exe, target);
        if (comptime std.mem.eql(u8, example.name, "website")) {
            embedDir(b, exe, httpxModule, "examples/website/dist", "embed_website");
        }

        const installExe = b.addInstallArtifact(exe, .{});
        buildAllExamples.dependOn(&installExe.step);
        const exampleStep = b.step("example-" ++ example.name, "Build " ++ example.name ++ " example");
        exampleStep.dependOn(&installExe.step);

        const runExe = b.addRunArtifact(exe);
        runExe.step.dependOn(&installExe.step);
        const runStep = b.step("run-" ++ example.name, "Run " ++ example.name ++ " example");
        runStep.dependOn(&runExe.step);
    }

    const runAllExamples = b.step("run-all-examples", "Run all examples sequentially");
    var previousRunStep: ?*std.Build.Step = null;

    inline for (examples) |example| {
        const exe = b.addExecutable(.{
            .name = "run-all-" ++ example.name,
            .root_module = b.createModule(.{
                .root_source_file = b.path(example.path),
                .target = target,
                .optimize = optimize,
            }),
        });
        exe.root_module.addImport("httpx", httpxModule);
        linkPlatformLibs(exe, target);
        if (comptime std.mem.eql(u8, example.name, "website")) {
            embedDir(b, exe, httpxModule, "examples/website/dist", "embed_website");
        }

        const installExe = b.addInstallArtifact(exe, .{});
        if (previousRunStep) |prev| {
            exe.step.dependOn(prev);
            installExe.step.dependOn(prev);
        }
        const runExe = b.addRunArtifact(exe);
        runExe.step.dependOn(&installExe.step);

        previousRunStep = &runExe.step;
    }

    if (previousRunStep) |last| {
        runAllExamples.dependOn(last);
    }

    const tests = b.addTest(.{
        .root_module = httpxRootModule(b, target, optimize, &deps),
    });
    linkPlatformLibs(tests, target);

    const runTests = b.addRunArtifact(tests);
    runTests.has_side_effects = true;
    const testStep = b.step("test", "Run unit tests");

    // Only run tests when target matches host; otherwise build test artifact only.
    if (target.result.os.tag == builtin.os.tag and target.result.cpu.arch == builtin.cpu.arch) {
        testStep.dependOn(&runTests.step);
    } else {
        const installTests = b.addInstallArtifact(tests, .{});
        testStep.dependOn(&installTests.step);
    }

    const benchExe = b.addExecutable(.{
        .name = "benchmark",
        .root_module = b.createModule(.{
            .root_source_file = b.path("bench/main.zig"),
            .target = target,
            .optimize = .ReleaseFast,
        }),
    });
    benchExe.root_module.addImport("httpx", httpxModule);
    linkPlatformLibs(benchExe, target);

    const installBench = b.addInstallArtifact(benchExe, .{});
    const runBench = b.addRunArtifact(benchExe);
    runBench.step.dependOn(&installBench.step);

    const benchStep = b.step("bench", "Run benchmarks");
    benchStep.dependOn(&runBench.step);

    const librootModule = httpxRootModule(b, target, optimize, &deps);

    const lib = b.addLibrary(.{
        .name = "httpx",
        .linkage = .static,
        .root_module = librootModule,
    });
    linkPlatformLibs(lib, target);

    b.installArtifact(lib);

    const docsStep = b.step("docs", "Generate library documentation");
    const installDocs = b.addInstallDirectory(.{
        .source_dir = lib.getEmittedDocs(),
        .install_dir = .prefix,
        .install_subdir = "docs",
    });
    docsStep.dependOn(&installDocs.step);

    const testAllStep = b.step("test-all", "Run tests, benchmarks, and all runnable examples");
    testAllStep.dependOn(testStep);
    testAllStep.dependOn(benchStep);
    testAllStep.dependOn(runAllExamples);
}
